let djangoSum = "Quentin Tarantino's gripping Western revenge tale set in the pre-Civil War era. The film follows Django, a freed slave turned bounty hunter, who joins forces with a German bounty hunter named Dr. King Schultz. Together, they embark on a mission to rescue Django's wife from a ruthless plantation owner, Calvin Candie. As they navigate the treacherous world of slavery and confront the horrors of racism, they also unravel a web of deceit and cruelty. With Tarantino's signature style, the film combines intense action, dark humor, and social commentary to shed light on the brutality of slavery and the enduring quest for justice."
let achillesSum = "a legendary figure from Greek mythology, known as the greatest warrior of the Trojan War. In Homer's epic poem, The Iliad, Achilles is a complex character driven by pride, honor, and the pursuit of glory. He is a formidable warrior with unmatched skill and strength, but his fatal flaw is his excessive pride, or hubris. Achilles is faced with numerous challenges throughout the poem, including conflicts with other Greek heroes, the loss of his comrade Patroclus, and his eventual confrontation with the Trojan prince, Hector. The story of Achilles serves as a cautionary tale about the consequences of unchecked pride and the fleeting nature of heroism."
let cloudAtlasSum = "a mind-bending film adaptation of David Mitchell's novel, directed by Lana and Andy Wachowski and Tom Tykwer. The story weaves together multiple narratives spanning different time periods, interconnected by the themes of love, fate, and the power of human connection. From a 19th-century sea voyage to a futuristic dystopian society, the film explores how the choices and actions of individuals ripple through time, leaving a lasting impact. It delves into the intricate relationships between characters played by a talented ensemble cast, challenging conventional notions of identity and showcasing the resilience of the human spirit."
let lotrRotkSum = "the epic conclusion to J.R.R. Tolkien's fantasy trilogy. The story follows Frodo Baggins and his loyal companions as they continue their perilous journey to Mount Doom to destroy the One Ring and defeat the dark lord Sauron. As the war for Middle-earth rages on, the fate of all races hangs in the balance. The film is filled with intense battles, emotional reunions, and sacrifices as the characters face their darkest fears and rise to the occasion. Ultimately, the triumph of good over evil is realized, but not without great loss and a bittersweet sense of closure."
let pinnSum = " a classic children's story written by Carlo Collodi. The tale follows the adventures of a wooden puppet named Pinocchio who dreams of becoming a real boy. Created by a kind-hearted woodcarver named Geppetto, Pinocchio embarks on a journey filled with mischievous escapades, learning valuable life lessons along the way. With the guidance of his conscience, the cricket Jiminy Cricket, Pinocchio faces numerous trials and temptations that test his honesty, loyalty, and bravery. Through his encounters with cunning characters like the crafty fox and the sly cat, Pinocchio gradually discovers the importance of honesty, kindness, and taking responsibility for his actions, ultimately earning his wish to become a real, flesh-and-blood boy"
let goodSum = " a heartfelt drama directed by Gus Van Sant. The film revolves around the life of Will Hunting, a brilliant but troubled young janitor working at the Massachusetts Institute of Technology (MIT). Will possesses an extraordinary talent for mathematics, unbeknownst to his co-workers and superiors. When a renowned mathematics professor discovers Will's potential, he encourages him to pursue a brighter future. However, Will's emotional scars and fear of abandonment make it challenging for him to embrace his true potential. With the help of an empathetic therapist named Sean Maguire, played by Robin Williams, Will begins to confront his inner demons, heal his wounds, and discover his own self-worth. As the story unfolds, Will navigates relationships, confronts his past, and learns the power of vulnerability, friendship, and seizing opportunities for personal growth."
let beautSum = "a biographical drama directed by Ron Howard. The film tells the inspiring true story of John Nash, a brilliant mathematician whose life takes an unexpected turn when he develops schizophrenia. As Nash's mental health deteriorates, he struggles to distinguish between reality and hallucinations, facing immense challenges in his personal and professional life. Despite the adversities, Nash's exceptional mind and perseverance prevail, and he makes groundbreaking contributions to the field of game theory. With the support of his devoted wife, Alicia, played by Jennifer Connelly, Nash learns to manage his condition and rebuild his life, demonstrating the power of love, resilience, and the human spirit in the face of adversity."
let benSum = " a fantasy drama directed by David Fincher. The film follows the extraordinary life of Benjamin Button, a man born with a peculiar condition that causes him to age in reverse. Starting as an old man, Benjamin grows younger with each passing year. As he navigates through life, Benjamin encounters a diverse array of experiences, relationships, and emotions that shape his perspective on love, loss, and the fleeting nature of time. Despite his unusual circumstances, Benjamin lives a full and remarkable life, ultimately finding love and acceptance in the arms of a kindred spirit. The film delves into themes of mortality, destiny, and the importance of cherishing each moment as Benjamin's extraordinary journey serves as a metaphorical exploration of the human condition."
export const moviesData = [
    {id: 1, title: "Lord of the Rings: Return of the King  ", videoId:"r5X-hFf6Bwo", year: "2008  ", src: "https://image.tmdb.org/t/p/original/dNsEaafO4huvqzVrlPuSQWIHOy0.jpg", summary: lotrRotkSum   , revenue: "$112,345,664"},
{id: 2, title: "Cloud Atlas",videoId:"hWnAqFyaQ5s",  year: "2012", src: "https://sf-fan.de/wp-content/uploads/2012/10/cloud_atlas_ver2_xxlg.jpg ", summary: cloudAtlasSum   , revenue: "$22,012,234 "},
{id: 3, title: "Achilles",videoId:"znTLzRJimeY",  year: "2004", src: "https://i.pinimg.com/736x/23/d6/b3/23d6b3b6bf2d53a690cb1bc46f9cc5fc.jpg", summary: achillesSum  , revenue: "$45,000,123"},
{id: 4, title: "Django Unchained", videoId:"0fUCuvNlOCg", year: "2012", src: "https://image.tmdb.org/t/p/original/aWdrrXWWejwXFEqiPR1kuK4WvIS.jpg", summary: djangoSum , revenue: "$62,012,344"},
{id: 5, title: "Pinnochio" , videoId: "GBgyVY_ClzQ", year: "1940", src: "https://filmfanatic.org/wp-content/uploads/2011/03/Pinocchio-Poster.png", summary: pinnSum, revenue: "$45,607,876"},
{id: 6, title: "Benjamin Button" , videoId: "iH6FdW39Hag", year: "2014", src: "https://images.squarespace-cdn.com/content/5233347fe4b00c95cda9e5d6/1412138997257-P4QCV12CTXL4KID9LYNZ/?content-type=image%2Fpng", summary: benSum, revenue: "$45,607,876"},
{id: 7, title: "Good Will Hunting" , videoId: "ReIJ1lbL-Q8", year: "1999", src: "https://image.tmdb.org/t/p/original/cRGwIKM1FdDvLCz0kxcNURWtyaS.jpg", summary: goodSum, revenue: "$45,607,876"},
{id: 8, title: "A Beautiful Mind" , videoId: "YWwAOutgWBQ", year: "2002", src: "https://img.moviesrankings.com/t/p/w1280/5mFpNMfRQl2GCSus1ijh0COFfwp.jpg", summary: beautSum, revenue: "$45,607,876"}
]